apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-site-deployment
  labels:
    app: bank-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank-site
  template:
    metadata:
      labels:
        app: bank-site
    spec:
  containers:
  - name: bank-site
    image: emma2323/bank-site:latest  # Updated image
    ports:
    - containerPort: 90
      name: http
    - containerPort: 9113
      name: metrics
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
